[build]
  command = "vite build"
  publish = "dist"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
